### ISSUE TITLE
Change the main branch to be called "master"?

### ISSUE THREAD

**Issue by itsdchen** [snobbytech/main#1]
When I pushed the initial thing, I had intended to make a pull request. But it looks like this project didn't have any branches anyway, so github just took the branch, accepted it, and made it the main branch. It's usually called master, so if you get a chance, would you be able to change it?

https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-user-account-settings/managing-the-default-branch-name-for-your-repositories

**Comment by snobbytech** [comment]
No problem. Name changed to master.

**Comment by itsdchen** [comment]
![Screenshot from 2021-08-04 12-52-29](https://user-images.githubusercontent.com/324044/128222258-f802f0b5-e61e-43c4-a2e1-64d840b2886b.png)
Just wanted to clarify - I'm talking about the branch, and not the name of the repository. The default branch here is called "backendmodels".

**Comment by snobbytech** [comment]
Got it. Changed the default branch name to 'master'. Let me know if this works?

**Comment by itsdchen** [comment]
Perfect, thanks!
